batch_size: 32
conv_layers: 2
dataset_name: CELEBA
depth: 3
dropout: 0.2
embedding_dim: 64
eval_frequency: 0.3
final_lr: 1.0e-05
first_hidden: 64
image_size: 64
initial_channels: 3
lr: 1.0e-3
max_time_steps: 400
n_epochs: 100
n_epochs_lr: 90
num_labels: 0
<<<<<<< HEAD
patience: 20
=======
num_workers: 4
patience: 25
>>>>>>> 4a47e90b2c7ea120832f7ba75cfce0644f2ef329
save_path: best_model2_CELEBA.pth
use_compile: true
